# Generated by Django 5.0.6 on 2024-05-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NPK_Experimentales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nro', models.IntegerField()),
                ('V_teo_1', models.FloatField()),
                ('V_teo_2', models.FloatField()),
                ('V_teo_3', models.FloatField()),
                ('Fecha', models.DateTimeField()),
                ('Valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NPK_Teoricos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nro', models.IntegerField()),
                ('V_teo_1', models.FloatField(blank=True, null=True)),
                ('V_teo_2', models.FloatField(blank=True, null=True)),
                ('V_teo_3', models.FloatField(blank=True, null=True)),
                ('Valid', models.BooleanField(default=True)),
            ],
        ),
    ]
