# Generated by Django 5.0.6 on 2024-05-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla_NPK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nro', models.CharField(max_length=100)),
                ('V_med_1', models.IntegerField()),
                ('V_teo_1', models.FloatField(blank=True, null=True)),
                ('V_med_2', models.IntegerField()),
                ('V_teo_2', models.FloatField(blank=True, null=True)),
                ('V_med_3', models.IntegerField()),
                ('V_teo_3', models.FloatField(blank=True, null=True)),
                ('Fecha', models.DateTimeField()),
            ],
        ),
    ]
